fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

lmi_school:
    resource: "@LmiSchoolBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: LmiSchoolBundle:Security:login }

login_check:
    pattern:   /login_check
