add_image:
    pattern:  /add
    defaults: { _controller: "LmiSchoolBundle:Image:add" }
    requirements:
        _method: GET

upload_image:
    pattern:  /
    defaults: { _controller: "LmiSchoolBundle:Image:upload" }
    requirements:
        _method: POST
