news_new:
    pattern:  /new
    defaults: { _controller: "LmiSchoolBundle:News:new" }

news_create:
    pattern:  /
    defaults: { _controller: "LmiSchoolBundle:News:create" }
    requirements: { _method: post }

news_edit:
    pattern:  /{identifier}/edit
    defaults: { _controller: "LmiSchoolBundle:News:edit" }

news_update:
    pattern:  /{identifier}
    defaults: { _controller: "LmiSchoolBundle:News:update" }
    requirements: { _method: post|put }

news_delete:
    pattern:  /{identifier}
    defaults: { _controller: "LmiSchoolBundle:News:delete" }
    requirements: { _method: delete }
