image_get:
    pattern:  /{id}/{size}
    defaults: { _controller: "LmiSchoolBundle:Image:get" }
    requirements:
        id: \d+
        size: (thumb|small|medium|large|extra)
        _method: GET

image_yandex:
    pattern:  /yandex
    defaults: { _controller: "LmiSchoolBundle:Image:yandex" }
