news:
    pattern:  /
    defaults: { _controller: "LmiSchoolBundle:News:index" }
    requirements: { _method: get }

news_show:
    pattern:  /{identifier}
    defaults: { _controller: "LmiSchoolBundle:News:show" }
    requirements: { _method: get }
