lmi_school_admin_news:
    resource: "@LmiSchoolBundle/Resources/config/routing/admin/news.yml"
    prefix:   /news

lmi_school_admin_teachers:
    resource: "@LmiSchoolBundle/Resources/config/routing/admin/teacher.yml"
    prefix:   /teachers

lmi_school_admin_pages:
    resource: "@LmiSchoolBundle/Resources/config/routing/admin/pages.yml"
    prefix:   /pages

lmi_school_admin_room:
    resource: "@LmiSchoolBundle/Resources/config/routing/admin/room.yml"
    prefix:   /rooms

lmi_school_admin_proxy:
    resource: "@LmiSchoolBundle/Resources/config/routing/admin/proxy.yml"
    prefix:   /proxy

