lmi_school_news:
    resource: "@LmiSchoolBundle/Resources/config/routing/common/news.yml"
    prefix:   /news

lmi_school_teachers:
    resource: "@LmiSchoolBundle/Resources/config/routing/common/teacher.yml"
    prefix:   /teachers

lmi_school_room:
    resource: "@LmiSchoolBundle/Resources/config/routing/common/room.yml"
    prefix:   /cabinets

lmi_school_page:
    resource: "@LmiSchoolBundle/Resources/config/routing/common/pages.yml"
    prefix:   /

lmi_school_proxy:
    resource: "@LmiSchoolBundle/Resources/config/routing/common/proxy.yml"
    prefix:   /proxy

yandex_fotki_config:
    pattern:  /proxy/fotki/config.json
    defaults:
        _controller: "FrameworkBundle:Template:template"
        template: 'LmiSchoolBundle::config.json.twig'
    options:
        expose: true