lmi_school_news:
    resource: "@LmiSchoolBundle/Resources/config/routing/common/news.yml"
    prefix:   /news

lmi_school_teachers:
    resource: "@LmiSchoolBundle/Resources/config/routing/common/teacher.yml"
    prefix:   /teachers

lmi_school_images:
    resource: "@LmiSchoolBundle/Resources/config/routing/common/images.yml"
    prefix:   /images

lmi_school_room:
    resource: "@LmiSchoolBundle/Resources/config/routing/common/room.yml"
    prefix:   /cabinets

lmi_school_page:
    resource: "@LmiSchoolBundle/Resources/config/routing/common/pages.yml"
    prefix:   /

